---

- name: Run RHEL8 CIS hardening
  hosts: localhost
  become: true
  roles:
    - role: "{{ playbook_dir }}"
      vars:
        rhel8cis_rule_5_2_4: false
        rhel8cis_authselect_custom_profile_name: openstack
      tags:
        - level1-server
        - level2-server

  pre_tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - chrony
          - qemu-guest-agent
        state: present

    - name: Enable chronyd service
      ansible.builtin.command: systemctl enable chronyd

  post_tasks:
    - name: Remove ssh key and directory
      ansible.builtin.file:
        state: absent
        path: '{{ item }}'
      with_items:
        - /etc/ssh/ssh_host_*
        - /home/almalinux/.ssh
        - /root/.ansible
